import type { Project, Experience, Blog, Education, Link, Stat } from "@/types";

export const portfolio = {
  name: "Bhavya Gulati",
  tagline: "Building software that matters.",
  intro: "Full-Stack Engineer with strong foundations in DSA, scalable web apps, and performant user-facing systems.",
  status: "Available for Backend / Full-Stack roles",
  email: "bhavyagulati651@gmail.com",
  phone: "+91 9311796190",
  links: [
    { label: "GitHub", url: "https://github.com/bhavyagulati123" },
    { label: "LinkedIn", url: "https://www.linkedin.com/in/bhavya-gulati-9434b71b4/" },
    { label: "X (Twitter)", url: "https://x.com/bhavya_gulati1" },
    { label: "LeetCode", url: "https://leetcode.com/u/bM2YSX9HqX/" },
  ] satisfies Link[],
  about: [
    "I'm a Full-Stack Engineer who believes great code should be invisible — users should only notice how effortlessly things work. From building real-time chat systems to designing AI pipeline editors, I enjoy crafting products that solve real problems.",
    "Currently interning at Hemitaverse, where I've optimized API latency by 30%, shipped 5+ production releases through CI/CD, and built scalable Next.js architectures. I thrive in Agile environments and care deeply about clean architecture and developer experience.",
    "When I'm not shipping features, you'll find me solving DSA problems on LeetCode, exploring generative AI, or contributing to projects that push me to learn something new.",
  ],
  stats: [
    { number: "5+", label: "Production Releases" },
    { number: "30%", label: "Latency Reduced" },
    { number: "7.6", label: "CGPA" },
    { number: "100%", label: "Sprint Delivery" },
  ] satisfies Stat[],
  experience: [
    {
      date: "June 2025 — Present",
      role: "Full-Stack Engineer Intern",
      company: "Hemitaverse (Remote)",
      points: [
        "Built a custom CRM software from scratch using Next.js and Node.js, enabling streamlined lead tracking, client management, and sales pipeline automation.",
        "Implemented technical SEO strategies — structured data, meta optimization, sitemap generation, and Core Web Vitals improvements — boosting organic search visibility.",
        "Led digital transformation initiatives, migrating legacy manual workflows to automated web-based systems, reducing operational overhead and improving team efficiency.",
        "Designed authentication & authorization middleware using JWT and role-based access control.",
        "Optimized REST API queries and database access patterns, reducing page load latency by 25–30%.",
        "Delivered 5+ CI/CD-based production releases and collaborated in Agile/Scrum sprints with 100% on-time delivery.",
      ],
    },
  ] satisfies Experience[],
  projects: [
    {
      icon: "⚡",
      name: "Visual AI Pipeline Builder",
      desc: "Node-based visual workflow editor for designing AI pipelines using directed acyclic graphs. Features dynamic template variable parsing, reusable BaseNode abstraction, and DFS-based cycle detection.",
      tags: ["React Flow", "Zustand", "FastAPI", "Python"],
      featured: true,
      featureHighlight: { main: "DAG Editor", sub: "DFS Cycle Detection" },
      github: "https://github.com/bhavyagulati/visual-ai-pipeline-builder",
      live: "https://visual-ai-pipeline-builder.vercel.app",
    },
    {
      icon: "🍽️",
      name: "One4U — Corporate Canteen Platform",
      desc: "Full-stack platform enabling real-time order tracking with Socket.IO, admin analytics dashboard with Chart.js, and GenAI-based food recommendations.",
      tags: ["React.js", "Node.js", "MongoDB", "Socket.IO"],
      github: "https://github.com/bhavyagulati/one4u",
      live: "https://one4u.vercel.app",
    },
    {
      icon: "💬",
      name: "Realtime Chat App",
      desc: "Real-time messaging system with WebSockets, online presence indicators, JWT authentication, and Zustand-powered global state management.",
      tags: ["MERN", "Tailwind CSS", "Zustand", "JWT"],
      github: "https://github.com/bhavyagulati/realtime-chat-app",
      live: "https://realtime-chat-app.onrender.com",
    },
    {
      icon: "🫁",
      name: "Pneumobot",
      desc: "Pneumonia detection chatbot using LLMs and Gradio. Features a dynamic scoring system to choose between custom prompts and Google Gemini for diagnostic responses.",
      tags: ["Python", "TensorFlow", "Keras", "Gradio"],
      github: "https://github.com/bhavyagulati/pneumobot",
    },
  ] satisfies Project[],
  skills: {
    Languages: ["JavaScript (ES6+)", "TypeScript", "Python", "C++", "SQL"],
    "Frameworks & Tools": ["React.js / Next.js", "Node.js / Express.js", "Django / FastAPI", "Socket.IO", "Tailwind CSS"],
    "Databases & Infra": ["MongoDB", "PostgreSQL", "Git / GitHub", "CI/CD", "Vercel / Render"],
  } as Record<string, string[]>,
  blogs: [
    {
      slug: "dag-validation-visual-pipeline-builders",
      tag: "Architecture",
      date: "Feb 2026",
      title: "Why DAG Validation Matters in Visual Pipeline Builders",
      excerpt: "How DFS-based cycle detection prevents broken AI workflows and what I learned building a pipeline editor from scratch.",
      content: [
        "When I started building the Visual AI Pipeline Builder, the first real challenge wasn't the drag-and-drop UI — it was making sure users couldn't create infinite loops in their workflows. A pipeline that loops back on itself would run forever, and that's not something you want in a production AI system.",
        "The core concept is simple: AI pipelines are directed acyclic graphs (DAGs). Each node processes data and passes it forward. If a cycle exists, the pipeline has no valid execution order. That's where DFS-based cycle detection comes in.",
        "I implemented a standard depth-first search with three states — unvisited, in-progress, and completed. When traversing the graph, if we encounter a node that's already in-progress, we've found a back edge, which means a cycle exists. The algorithm runs in O(V + E) time, making it efficient even for complex pipelines.",
        "One tricky part was providing useful error feedback. Simply saying 'cycle detected' isn't helpful. I tracked the cycle path during DFS so the UI could highlight exactly which nodes form the loop, letting users fix the issue visually.",
        "The BaseNode abstraction was another key decision. Every node type — LLM call, data transform, conditional branch — extends BaseNode, which handles port connections, validation, and template variable parsing. This made adding new node types trivial: just define the config schema and processing logic.",
        "Template variables (like {{input.text}}) are parsed dynamically and resolved at execution time. The parser validates that all referenced variables exist in the upstream node outputs before the pipeline runs, catching configuration errors early.",
        "The biggest takeaway: validation logic in visual editors should be real-time and specific. Don't wait until the user hits 'Run' to tell them something is wrong. Validate on every connection change, and show exactly what's broken and where.",
      ],
    },
    {
      slug: "scaling-websockets-chat-app",
      tag: "Real-time",
      date: "Jan 2026",
      title: "Scaling WebSockets — Lessons from Building a Chat App",
      excerpt: "Handling concurrent connections, online presence, and state management patterns for real-time applications.",
      content: [
        "Building a real-time chat app sounds straightforward until you start dealing with connection management, presence tracking, and state synchronization across multiple clients. Here's what I learned building one with Socket.IO and the MERN stack.",
        "The first decision was choosing between polling and WebSockets. Polling is simpler but introduces latency and wastes bandwidth. WebSockets maintain a persistent connection, enabling instant message delivery. For a chat app, the choice was obvious — but WebSockets come with their own complexity.",
        "Connection lifecycle management was the first hurdle. Users connect, disconnect, switch tabs, lose network, and reconnect constantly. I implemented heartbeat checks and reconnection logic with exponential backoff. Socket.IO handles much of this, but you still need to manage application-level state when connections drop.",
        "Online presence was surprisingly complex. Simply tracking socket connections isn't enough — a user might have multiple tabs open. I maintained a per-user connection count on the server. A user is 'online' when their count is greater than zero and 'offline' when it drops to zero. Broadcasting presence changes to all connected clients required careful batching to avoid flooding the network.",
        "State management on the client was where Zustand proved invaluable. Chat apps have deeply nested state — conversations, messages, read receipts, typing indicators, user statuses. Zustand's flat store pattern with selective subscriptions kept re-renders minimal. Components only update when their specific slice of state changes.",
        "JWT authentication with WebSockets needed a different approach than REST APIs. I passed the token during the Socket.IO handshake and validated it in middleware before allowing the connection. Token refresh was handled by disconnecting and reconnecting with the new token.",
        "The key lesson: real-time apps need to be designed for failure. Connections will drop, messages will arrive out of order, and state will get out of sync. Build reconciliation into your architecture from day one, not as an afterthought.",
      ],
    },
    {
      slug: "cicd-pipelines-that-save-time",
      tag: "DevOps",
      date: "Dec 2025",
      title: "CI/CD Pipelines That Actually Save Time",
      excerpt: "What I learned shipping 5+ production releases at Hemitaverse — and the mistakes that taught me the most.",
      content: [
        "Before my internship at Hemitaverse, CI/CD was something I understood in theory. After shipping 5+ production releases, I learned that the gap between 'knowing about CI/CD' and 'having CI/CD that actually works' is enormous.",
        "The first mistake was treating the pipeline as a one-time setup. I configured a basic build-test-deploy flow and assumed it would just work. It didn't. Tests that passed locally failed in CI because of environment differences. Builds that worked fine took 15 minutes because of uncached dependencies. The pipeline was technically correct but practically useless.",
        "Caching was the single biggest improvement. Installing node_modules from scratch on every run added 3-4 minutes. After configuring proper dependency caching, that dropped to seconds. The same principle applied to Docker layers and build artifacts. Cache aggressively, invalidate precisely.",
        "The second big lesson was about test strategy in CI. Running the entire test suite on every push is wasteful. I set up the pipeline to run linting and type checks first (fast, catches most issues), then unit tests (medium), then integration tests (slow, only on PR merges). Fast feedback loops mean developers fix issues before they compound.",
        "Deployment strategy evolved too. We started with manual deployments and moved to automated staging deploys on PR merge, with production deploys triggered by release tags. Having a staging environment that mirrors production caught issues that would have been embarrassing in prod — especially around environment variables and API configurations.",
        "Rollback planning was something I initially ignored. The first time a production deploy broke something, we scrambled. After that, every release included a documented rollback procedure. Automated rollbacks based on health checks would have been even better, and that's something I'd prioritize in future setups.",
        "The biggest takeaway: CI/CD isn't about the tools, it's about the feedback loop. The faster developers know something is broken, the cheaper it is to fix. Optimize for speed of feedback, not comprehensiveness of checks.",
      ],
    },
  ] satisfies Blog[],
  education: [
    {
      degree: "B.Tech in Information Technology",
      school: "Maharaja Surajmal Institute of Technology, New Delhi",
      period: "Aug 2022 – June 2026",
      grade: "CGPA: 7.6/10",
    },
    {
      degree: "Class XII (CBSE)",
      school: "Spring Meadows Public School",
      period: "2021",
      grade: "84%",
    },
  ] satisfies Education[],
  achievements: [
    "Student Organizing Committee Member — 2nd International Conference on AI and Applications, MSIT (Springer).",
    "Completed 6-week hands-on training in Generative AI — built Pneumobot, a pneumonia detection chatbot.",
  ],
};
